# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milk_recipts.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(498, 453)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(40, 10, 411, 421))
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txt_sup_code = QtGui.QLineEdit(self.frame)
        self.txt_sup_code.setGeometry(QtCore.QRect(100, 100, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_sup_code.setFont(font)
        self.txt_sup_code.setObjectName(_fromUtf8("txt_sup_code"))
        self.txt_sup_name = QtGui.QLineEdit(self.frame)
        self.txt_sup_name.setGeometry(QtCore.QRect(100, 130, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_sup_name.setFont(font)
        self.txt_sup_name.setObjectName(_fromUtf8("txt_sup_name"))
        self.pb_add = QtGui.QPushButton(self.frame)
        self.pb_add.setGeometry(QtCore.QRect(30, 380, 75, 23))
        self.pb_add.setObjectName(_fromUtf8("pb_add"))
        self.pb_update = QtGui.QPushButton(self.frame)
        self.pb_update.setGeometry(QtCore.QRect(110, 380, 75, 23))
        self.pb_update.setObjectName(_fromUtf8("pb_update"))
        self.pb_delete = QtGui.QPushButton(self.frame)
        self.pb_delete.setGeometry(QtCore.QRect(190, 380, 75, 23))
        self.pb_delete.setObjectName(_fromUtf8("pb_delete"))
        self.pb_view = QtGui.QPushButton(self.frame)
        self.pb_view.setGeometry(QtCore.QRect(270, 380, 75, 23))
        self.pb_view.setObjectName(_fromUtf8("pb_view"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.dateEdit = QtGui.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(100, 70, 110, 22))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(20, 170, 20, 191))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 210, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 240, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 270, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(110, 170, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(200, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.txt_mqty = QtGui.QLineEdit(self.frame)
        self.txt_mqty.setGeometry(QtCore.QRect(110, 210, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_mqty.setFont(font)
        self.txt_mqty.setObjectName(_fromUtf8("txt_mqty"))
        self.txt_mfat = QtGui.QLineEdit(self.frame)
        self.txt_mfat.setGeometry(QtCore.QRect(110, 240, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_mfat.setFont(font)
        self.txt_mfat.setObjectName(_fromUtf8("txt_mfat"))
        self.txt_msnf = QtGui.QLineEdit(self.frame)
        self.txt_msnf.setGeometry(QtCore.QRect(110, 270, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_msnf.setFont(font)
        self.txt_msnf.setObjectName(_fromUtf8("txt_msnf"))
        self.txt_esnf = QtGui.QLineEdit(self.frame)
        self.txt_esnf.setGeometry(QtCore.QRect(190, 270, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_esnf.setFont(font)
        self.txt_esnf.setObjectName(_fromUtf8("txt_esnf"))
        self.txt_eqty = QtGui.QLineEdit(self.frame)
        self.txt_eqty.setGeometry(QtCore.QRect(190, 210, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_eqty.setFont(font)
        self.txt_eqty.setObjectName(_fromUtf8("txt_eqty"))
        self.txt_efat = QtGui.QLineEdit(self.frame)
        self.txt_efat.setGeometry(QtCore.QRect(190, 240, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_efat.setFont(font)
        self.txt_efat.setObjectName(_fromUtf8("txt_efat"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(40, 300, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(40, 330, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(270, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.txt_tqty = QtGui.QLineEdit(self.frame)
        self.txt_tqty.setGeometry(QtCore.QRect(270, 210, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_tqty.setFont(font)
        self.txt_tqty.setObjectName(_fromUtf8("txt_tqty"))
        self.txt_mrate = QtGui.QLineEdit(self.frame)
        self.txt_mrate.setGeometry(QtCore.QRect(110, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_mrate.setFont(font)
        self.txt_mrate.setObjectName(_fromUtf8("txt_mrate"))
        self.txt_erate = QtGui.QLineEdit(self.frame)
        self.txt_erate.setGeometry(QtCore.QRect(190, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_erate.setFont(font)
        self.txt_erate.setObjectName(_fromUtf8("txt_erate"))
        self.txt_mamt = QtGui.QLineEdit(self.frame)
        self.txt_mamt.setGeometry(QtCore.QRect(110, 330, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_mamt.setFont(font)
        self.txt_mamt.setObjectName(_fromUtf8("txt_mamt"))
        self.txt_eamt = QtGui.QLineEdit(self.frame)
        self.txt_eamt.setGeometry(QtCore.QRect(190, 330, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_eamt.setFont(font)
        self.txt_eamt.setObjectName(_fromUtf8("txt_eamt"))
        self.txt_tamt = QtGui.QLineEdit(self.frame)
        self.txt_tamt.setGeometry(QtCore.QRect(270, 330, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_tamt.setFont(font)
        self.txt_tamt.setObjectName(_fromUtf8("txt_tamt"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(170, 170, 20, 191))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(250, 170, 20, 191))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(30, 160, 321, 20))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(340, 170, 20, 191))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(30, 350, 321, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(90, 170, 20, 191))
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(30, 190, 321, 16))
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "aavin::Tirunelveli", None))
        self.label_2.setText(_translate("Dialog", "Milk Recipt Entry", None))
        self.label_3.setText(_translate("Dialog", "Sup Code", None))
        self.label_4.setText(_translate("Dialog", "Sup Name", None))
        self.pb_add.setText(_translate("Dialog", "Add New", None))
        self.pb_update.setText(_translate("Dialog", "Update", None))
        self.pb_delete.setText(_translate("Dialog", "Remove", None))
        self.pb_view.setText(_translate("Dialog", "View", None))
        self.label_5.setText(_translate("Dialog", "Date", None))
        self.label_6.setText(_translate("Dialog", "Qty", None))
        self.label_7.setText(_translate("Dialog", "Fat", None))
        self.label_8.setText(_translate("Dialog", "Snf", None))
        self.label_9.setText(_translate("Dialog", "Shift A", None))
        self.label_10.setText(_translate("Dialog", "Shift B", None))
        self.label_11.setText(_translate("Dialog", "Rate", None))
        self.label_12.setText(_translate("Dialog", "Amount", None))
        self.label_13.setText(_translate("Dialog", "Total", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

